---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/blog
  label: Blogs
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - doc
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.72.0
  - PREVIEW_IP=0.0.0.0
  - PREVIEW_PORT=8080
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: technical-blog/hugo:node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run technical-blog:instant-preview
version: 0.42.2
